### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by dprevite** [nicoSWD/put.io-api-v2#4]
When I try this, tweaked from the docs:

    // Upload a file.
    $file = '/path/to/file.torrent';
    $putio->files->upload($file);

I'm getting the following response from the API even though other API calls (getting files) work just fine.

    {
      "error_message": "The server could not verify that you are authorized to access the URL requested.  You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.", 
      "error_type": "Unauthorized", 
      "error_uri": "http://api.put.io/v2/docs", 
      "status": "ERROR", 
      "status_code": 401
    }

**Comment by nicoSWD** [comment]
The issue has been addressed.

Thanks again!
