### ISSUE TITLE
put.io certificate changed?

### ISSUE THREAD

**Issue by enko** [nicoSWD/put.io-api-v2#7]
My application does not work any more:

[2015-12-06 10:52:13] putio-unwrapper.ERROR: Failed to excute API. {"error":"SSL certificate problem: self signed certificate in certificate chain"} []

I tried to replace `StarfieldClass2CA.pem` by the comodo certs that are in the chain of `api.put.io`, but still got the same error.

**Comment by ablyler** [comment]
Yes it did, it changed to Comodo: https://www.sslshopper.com/ssl-checker.html#hostname=api.put.io

**Comment by nicoSWD** [comment]
Should be fixed now. Thanks to the both of you!
